# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='_command_line',
            field=models.CharField(editable=False, max_length=255, null=True, verbose_name='Final generated command line'),
        ),
    ]
