# Generated by Django 3.0.3 on 2020-02-19 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runner',
            name='binary_file',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='binary_file',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='runner',
        ),
        migrations.AlterField(
            model_name='aparam',
            name='required',
            field=models.NullBooleanField(choices=[(False, 'Optional'), (True, 'Required'), (None, 'Not submitted by user')], default=True, help_text='Submitted and/or Required', verbose_name='Required'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='clazz',
            field=models.CharField(help_text='This is the concrete class used to perform job execution', max_length=100, null=True, verbose_name='Adapter object'),
        ),
        migrations.AlterField(
            model_name='service',
            name='runner',
            field=models.ForeignKey(db_column='runner_id', help_text='Service job runs configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_service_runs', to='core.Runner', verbose_name='Computing infrastructure'),
        ),
        migrations.AlterField(
            model_name='submissionoutput',
            name='from_input',
            field=models.ForeignKey(blank=True, default=None, help_text='Is valuated from an input', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_outputs', to='core.AParam'),
        ),
    ]
