# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0002_job__command_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_jobs', to='waves.Submission'),
        ),
    ]
