# Generated by Django 3.0.3 on 2020-02-19 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200220_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='runner',
            field=models.ForeignKey(db_column='runner_id', help_text='Service job runs configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_submission_runs', to='core.Runner', verbose_name='Computing infrastructure'),
        ),
    ]
