# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0003_auto_20170629_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='notify',
            field=models.BooleanField(default=False, editable=False, verbose_name='Notify this result'),
        ),
        migrations.AddField(
            model_name='job',
            name='service',
            field=models.CharField(default='N/A', editable=False, max_length=255, null=True, verbose_name='Issued from service'),
        ),
    ]
