# Generated by Django 3.0.3 on 2020-02-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_submission_runner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparam',
            name='required',
            field=models.NullBooleanField(choices=[(None, 'Not submitted by user'), (True, 'Required'), (False, 'Optional')], default=True, help_text='Submitted and/or Required', verbose_name='Required'),
        ),
    ]
