# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0004_auto_20170629_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='service',
            field=models.CharField(default='', editable=False, max_length=255, null=True, verbose_name='Issued from service'),
        ),
    ]
