# Generated by Django 3.0.3 on 2020-02-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200224_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparam',
            name='required',
            field=models.NullBooleanField(choices=[(False, 'Optional'), (None, 'Not submitted by user'), (True, 'Required')], default=True, help_text='Submitted and/or Required', verbose_name='Required'),
        ),
        migrations.AlterUniqueTogether(
            name='adaptorinitparam',
            unique_together=set(),
        ),
    ]
