# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0006_auto_20170629_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_jobs', to='waves.Submission'),
        ),
        migrations.AlterField(
            model_name='jobinput',
            name='param_type',
            field=models.IntegerField(choices=[(2, '-[name] value'), (1, '--[name]=value'), (3, '-[name]'), (5, '--[name]'), (4, 'Posix')], default=4, editable=False, null=True, verbose_name='Parameter Type'),
        ),
    ]
