language: python
python:
  - "2.7"
env:
  -DJANGO=3.0
install:
  - docker run -d -h sge.local -p 10022:22 agaveapi/gridengine
  - pip install -r requirements.txt
  - pip install coverage==4.5.1
script:
  - coverage run --source='.' manage.py test waves