# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 11:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeatedgroup',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_groups', to=settings.WCORE_SUBMISSION_MODEL),
        ),
        migrations.AlterField(
            model_name='submissionexitcode',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exit_codes', to=settings.WCORE_SUBMISSION_MODEL),
        ),
    ]
