# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionoutput',
            name='extension',
            field=models.CharField(blank=True, default='', help_text='Leave blank accept all, or set in file pattern', max_length=15, verbose_name='File extension'),
        ),
    ]
