# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid
import waves.wcore.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('wcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBinaryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp', verbose_name='Created on')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Last update timestamp', verbose_name='Last Update')),
                ('slug', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(max_length=255, verbose_name='Binary file label')),
                ('binary', models.FileField(storage=waves.wcore.utils.storage.BinaryStorage(), upload_to=waves.wcore.utils.storage.binary_directory, verbose_name='Binary file')),
            ],
            options={
                'verbose_name': 'Binary file',
                'verbose_name_plural': 'Binaries files',
            },
        ),
    ]
