# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobinput',
            name='command_type',
        ),
        migrations.AddField(
            model_name='jobinput',
            name='cmd_format',
            field=models.IntegerField(choices=[(0, 'Not used in command'), (2, '-[name] value'), (1, '--[name]=value'), (3, '-[name]'), (5, '--[name]'), (6, '[name]=value'), (4, 'value')], default=4, editable=False, null=True, verbose_name='Parameter Type'),
        ),
        migrations.AlterField(
            model_name='aparam',
            name='cmd_format',
            field=models.IntegerField(choices=[(0, 'Not used in command'), (2, '-[name] value'), (1, '--[name]=value'), (3, '-[name]'), (5, '--[name]'), (6, '[name]=value'), (4, 'value')], default=2, help_text='Command line pattern', verbose_name='Command line format'),
        ),
        migrations.AlterField(
            model_name='job',
            name='_status',
            field=models.IntegerField(choices=[(-1, 'Undefined'), (0, 'Created'), (1, 'Prepared'), (2, 'Queued'), (3, 'Running'), (4, 'Suspended'), (5, 'Run completed, pending data retrieval'), (6, 'Results data retrieved'), (7, 'Cancelled'), (8, 'Warnings'), (9, 'Error')], default=0, verbose_name='Job status'),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Undefined'), (0, 'Created'), (1, 'Prepared'), (2, 'Queued'), (3, 'Running'), (4, 'Suspended'), (5, 'Run completed, pending data retrieval'), (6, 'Results data retrieved'), (7, 'Cancelled'), (8, 'Warnings'), (9, 'Error')], help_text='History job status', null=True, verbose_name='Job Status'),
        ),
    ]
