# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcore', '0002_auto_20171003_1154'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joboutput',
            unique_together=set([('api_name', 'job')]),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set([]),
        ),
    ]
