# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wcore', '0002_servicebinaryfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='availability',
            field=models.IntegerField(choices=[(0, 'Not Available'), (1, 'Available on web only'), (2, 'Available on api only'), (3, 'Available on both api and web')], default=3, verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='submissionoutput',
            name='from_input',
            field=models.ForeignKey(blank=True, default=None, help_text='Is valuated from an input', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_outputs', to='wcore.AParam'),
        ),
    ]
