# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcore', '0002_auto_20180214_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='_adaptor',
            field=models.TextField(editable=False, null=True, verbose_name='Adapter classed used for this Job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='exit_code',
            field=models.IntegerField(default=0, help_text='Job exit code on relative adapter', verbose_name='Job system exit code'),
        ),
        migrations.AlterField(
            model_name='jobinput',
            name='remote_input_id',
            field=models.CharField(editable=False, max_length=255, null=True, verbose_name='Remote input ID (on adapter)'),
        ),
        migrations.AlterField(
            model_name='joboutput',
            name='remote_output_id',
            field=models.CharField(editable=False, max_length=255, null=True, verbose_name='Remote output ID (on adapter)'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='clazz',
            field=models.CharField(help_text='This is the concrete class used to perform job execution', max_length=100, verbose_name='adapter object'),
        ),
    ]
