# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcore', '0002_auto_20170926_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileinput',
            options={'ordering': ['order'], 'verbose_name': 'File input', 'verbose_name_plural': 'Files inputs'},
        ),
        migrations.AlterField(
            model_name='aparam',
            name='cmd_format',
            field=models.IntegerField(choices=[(0, 'Not used in final command'), (6, '[name]=value'), (2, '-[name] value'), (1, '--[name]=value'), (3, '-[name]'), (5, '--[name]'), (4, 'value')], default=2, help_text='Command line pattern', verbose_name='Command line format'),
        ),
        migrations.AlterField(
            model_name='aparam',
            name='required',
            field=models.NullBooleanField(choices=[(None, 'Not submitted by user'), (True, 'Required'), (False, 'Optional')], default=True, help_text='Submitted and/or Required', verbose_name='Required'),
        ),
        migrations.AlterField(
            model_name='jobinput',
            name='cmd_format',
            field=models.IntegerField(choices=[(0, 'Not used in final command'), (6, '[name]=value'), (2, '-[name] value'), (1, '--[name]=value'), (3, '-[name]'), (5, '--[name]'), (4, 'value')], default=4, editable=False, null=True, verbose_name='Parameter Type'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
