# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcore', '0003_auto_20171121_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='authors',
            field=models.CharField(help_text='Tools authors', max_length=255, null=True, verbose_name='Authors'),
        ),
        migrations.AddField(
            model_name='service',
            name='citations',
            field=models.CharField(help_text='Citation link (Bibtex format)', max_length=500, null=True, verbose_name='Citation link'),
        ),
    ]
