# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcore', '0004_auto_20170911_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinput',
            name='max_size',
            field=models.BigIntegerField(default=20480, help_text='in Ko', verbose_name='Allowed file size '),
        ),
    ]
