# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcore', '0004_auto_20171211_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='api_on',
        ),
        migrations.RemoveField(
            model_name='service',
            name='web_on',
        ),
    ]
