# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcore', '0005_auto_20171213_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='restricted_client',
            field=models.ManyToManyField(blank=True, help_text="Public access is granted to everyone, If status is 'Restricted' you may restrict access to specific users here.", related_name='wcore_service_restricted_services', to=settings.AUTH_USER_MODEL, verbose_name='Restricted clients'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.IntegerField(choices=[[0, 'Draft'], [1, 'Test'], [4, 'Only registered'], [2, 'Restricted'], [3, 'Public']], default=0, help_text='Service online status'),
        ),
    ]
