# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcore', '0005_auto_20170911_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aparam',
            options={'base_manager_name': 'base_objects', 'ordering': ['order'], 'verbose_name': 'Input', 'verbose_name_plural': 'Inputs'},
        ),
        migrations.AlterField(
            model_name='integerparam',
            name='step',
            field=models.IntegerField(blank=True, default=1, help_text='Step to increment/decrement values', verbose_name='Step'),
        ),
    ]
