# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wcore', '0006_auto_20171213_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinput',
            name='allow_copy_paste',
            field=models.BooleanField(default=False, help_text='Set whether file input field should add a copy/paste text field', verbose_name='Allow copy paste in forms'),
        ),
        migrations.AlterField(
            model_name='aparam',
            name='api_name',
            field=models.CharField(blank=True, help_text='App short code, used in url, leave blank for automatic setup', max_length=100, null=True, verbose_name='App short code'),
        ),
        migrations.AlterField(
            model_name='aparam',
            name='cmd_format',
            field=models.IntegerField(choices=[(0, '-- Not used in job command line--'), (6, 'Assigned named parameter: [name]=value'), (2, 'Named short parameter: -[name] value'), (1, 'Named assigned long parameter: --[name]=value'), (3, 'Named short option: -[name]'), (5, 'Named long option: --[name]'), (4, 'Positional parameter: value')], default=2, help_text='Command line pattern', verbose_name='Command line format'),
        ),
        migrations.AlterField(
            model_name='aparam',
            name='required',
            field=models.NullBooleanField(choices=[(True, 'Required'), (None, 'Not submitted by user'), (False, 'Optional')], default=True, help_text='Submitted and/or Required', verbose_name='Required'),
        ),
        migrations.AlterField(
            model_name='jobinput',
            name='api_name',
            field=models.CharField(blank=True, help_text='App short code, used in url, leave blank for automatic setup', max_length=100, null=True, verbose_name='App short code'),
        ),
        migrations.AlterField(
            model_name='jobinput',
            name='cmd_format',
            field=models.IntegerField(choices=[(0, '-- Not used in job command line--'), (6, 'Assigned named parameter: [name]=value'), (2, 'Named short parameter: -[name] value'), (1, 'Named assigned long parameter: --[name]=value'), (3, 'Named short option: -[name]'), (5, 'Named long option: --[name]'), (4, 'Positional parameter: value')], default=4, editable=False, null=True, verbose_name='Parameter Type'),
        ),
        migrations.AlterField(
            model_name='joboutput',
            name='api_name',
            field=models.CharField(blank=True, help_text='App short code, used in url, leave blank for automatic setup', max_length=100, null=True, verbose_name='App short code'),
        ),
        migrations.AlterField(
            model_name='service',
            name='api_name',
            field=models.CharField(blank=True, help_text='App short code, used in url, leave blank for automatic setup', max_length=100, null=True, verbose_name='App short code'),
        ),
        migrations.AlterField(
            model_name='service',
            name='runner',
            field=models.ForeignKey(help_text='Service job runs configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wcore_service_runs', to='wcore.Runner', verbose_name='Execution environment'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.IntegerField(choices=[[0, 'Draft (only creator)'], [1, 'Staff (Team members)'], [4, 'Registered'], [2, 'Restricted'], [3, 'Public']], default=0, help_text='Service online status'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='api_name',
            field=models.CharField(blank=True, help_text='App short code, used in url, leave blank for automatic setup', max_length=100, null=True, verbose_name='App short code'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='availability',
            field=models.IntegerField(choices=[(0, 'Disabled API'), (1, 'Enabled API')], default=1, verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='runner',
            field=models.ForeignKey(help_text='Service job runs configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wcore_submission_runs', to='wcore.Runner', verbose_name='Execution environment'),
        ),
        migrations.AlterField(
            model_name='submissionoutput',
            name='api_name',
            field=models.CharField(blank=True, help_text='App short code, used in url, leave blank for automatic setup', max_length=100, null=True, verbose_name='App short code'),
        ),
    ]
