# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcore', '0007_auto_20170913_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aparam',
            options={'base_manager_name': 'base_objects', 'ordering': ('order',), 'verbose_name': 'Input', 'verbose_name_plural': 'Inputs'},
        ),
        migrations.AlterField(
            model_name='aparam',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobinput',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='joboutput',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repeatedgroup',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
