
# Generated by Django 1.11.8 on 2018-03-12 12:44


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WavesApiUser',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Origin Site')),
                ('ip_list', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ip List')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waves_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Waves Api key',
                'verbose_name_plural': 'Waves Api keys',
            },
        ),
    ]
