from collections import namedtuple

from django.utils.translation import ugettext as _

JOB_UNDEFINED = -1
JOB_CREATED = 0
JOB_PREPARED = 1
JOB_QUEUED = 2
JOB_RUNNING = 3
JOB_SUSPENDED = 4
JOB_COMPLETED = 5
JOB_TERMINATED = 6
JOB_CANCELLED = 7
JOB_ERROR = 9

STR_JOB_UNDEFINED = _('Undefined')
STR_JOB_CREATED = _('Created')
STR_JOB_PREPARED = _('Prepared')
STR_JOB_QUEUED = _('Queued')
STR_JOB_RUNNING = _('Running')
STR_JOB_COMPLETED = _('Run completed')
STR_JOB_TERMINATED = _('Completed')
STR_JOB_CANCELLED = _('Cancelled')
STR_JOB_SUSPENDED = _('Suspended')
STR_JOB_ERROR = _('Error')


STATUS_LIST = [
    (JOB_UNDEFINED, STR_JOB_UNDEFINED),
    (JOB_CREATED, STR_JOB_CREATED),
    (JOB_PREPARED, STR_JOB_PREPARED),
    (JOB_QUEUED, STR_JOB_QUEUED),
    (JOB_RUNNING, STR_JOB_RUNNING),
    (JOB_SUSPENDED, STR_JOB_SUSPENDED),
    (JOB_COMPLETED, STR_JOB_COMPLETED),
    (JOB_TERMINATED, STR_JOB_TERMINATED),
    (JOB_CANCELLED, STR_JOB_CANCELLED),
    (JOB_ERROR, STR_JOB_ERROR),
]
NEXT_STATUS = {
    JOB_CREATED: JOB_PREPARED,
    JOB_PREPARED: JOB_QUEUED,
    JOB_QUEUED: JOB_RUNNING,
    JOB_RUNNING: JOB_COMPLETED,
    JOB_COMPLETED: JOB_TERMINATED
}
PENDING_STATUS = (JOB_CREATED,
                  JOB_PREPARED,
                  JOB_QUEUED,
                  JOB_RUNNING)

STATUS_MAP = {
    JOB_UNDEFINED: STR_JOB_UNDEFINED,
    JOB_CREATED: STR_JOB_CREATED,
    JOB_PREPARED: STR_JOB_PREPARED,
    JOB_QUEUED: STR_JOB_QUEUED,
    JOB_RUNNING: STR_JOB_RUNNING,
    JOB_SUSPENDED: STR_JOB_SUSPENDED,
    JOB_COMPLETED: STR_JOB_COMPLETED,
    JOB_TERMINATED: STR_JOB_TERMINATED,
    JOB_CANCELLED: STR_JOB_CANCELLED,
    JOB_ERROR: STR_JOB_ERROR,
}
JobRunDetails = namedtuple("JobRunDetails",
                           ['id', 'slug', 'job_remote_id', 'name', 'exit_code', 'created', 'started',
                            'finished', 'extra'])